{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "eca2cb1c-a6f4-43c9-bedd-8764eb752e83",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Username: \n",
      "Password: \n",
      "Remember Me: False\n"
     ]
    }
   ],
   "source": [
    "import customtkinter as ctk\n",
    "\n",
    "# ---------------- COLORS ---------------\n",
    "DARK_BROWN = \"#4a2c1d\"\n",
    "MID_BROWN = \"#7b4b2a\"\n",
    "LIGHT_SAND = \"#f4e8d3\"\n",
    "TEXT_BROWN = \"#3b2416\"\n",
    "BUTTON_BROWN = \"#b27a4d\"\n",
    "\n",
    "class LoginScreen(ctk.CTk):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "\n",
    "        self.title(\"Appname - Login\")\n",
    "        self.geometry(\"900x600\")\n",
    "        self.configure(fg_color=DARK_BROWN)\n",
    "\n",
    "        # Main Panel (the light box in the center)\n",
    "        self.container = ctk.CTkFrame(\n",
    "            self,\n",
    "            fg_color=LIGHT_SAND,\n",
    "            corner_radius=20,\n",
    "            width=350,\n",
    "            height=420\n",
    "        )\n",
    "        self.container.place(relx=0.5, rely=0.5, anchor=\"center\")\n",
    "\n",
    "        # Title\n",
    "        self.title_label = ctk.CTkLabel(\n",
    "            self.container,\n",
    "            text=\"Login\",\n",
    "            font=(\"Georgia\", 32, \"bold\"),\n",
    "            text_color=TEXT_BROWN\n",
    "        )\n",
    "        self.title_label.place(relx=0.5, y=60, anchor=\"center\")\n",
    "\n",
    "        # Username Input\n",
    "        self.username_entry = ctk.CTkEntry(\n",
    "            self.container,\n",
    "            width=250,\n",
    "            height=40,\n",
    "            placeholder_text=\"Username\",\n",
    "            fg_color=\"white\",\n",
    "            text_color=\"black\",\n",
    "            border_color=MID_BROWN,\n",
    "            border_width=2\n",
    "        )\n",
    "        self.username_entry.place(relx=0.5, y=150, anchor=\"center\")\n",
    "\n",
    "        # Password Input\n",
    "        self.password_entry = ctk.CTkEntry(\n",
    "            self.container,\n",
    "            width=250,\n",
    "            height=40,\n",
    "            placeholder_text=\"Password\",\n",
    "            fg_color=\"white\",\n",
    "            text_color=\"black\",\n",
    "            border_color=MID_BROWN,\n",
    "            border_width=2,\n",
    "            show=\"*\"\n",
    "        )\n",
    "        self.password_entry.place(relx=0.5, y=210, anchor=\"center\")\n",
    "\n",
    "        # Remember Me\n",
    "        self.remember_var = ctk.BooleanVar()\n",
    "        self.remember_check = ctk.CTkCheckBox(\n",
    "            self.container,\n",
    "            text=\"Remember Me\",\n",
    "            variable=self.remember_var,\n",
    "            fg_color=MID_BROWN,\n",
    "            text_color=TEXT_BROWN,\n",
    "            checkbox_width=20,\n",
    "            checkbox_height=20\n",
    "        )\n",
    "        self.remember_check.place(relx=0.5, y=260, anchor=\"center\")\n",
    "\n",
    "        # Login Button\n",
    "        self.login_button = ctk.CTkButton(\n",
    "            self.container,\n",
    "            text=\"Login\",\n",
    "            width=180,\n",
    "            height=45,\n",
    "            fg_color=BUTTON_BROWN,\n",
    "            hover_color=MID_BROWN,\n",
    "            corner_radius=10,\n",
    "            command=self.handle_login\n",
    "        )\n",
    "        self.login_button.place(relx=0.5, y=330, anchor=\"center\")\n",
    "\n",
    "    # Handle login button click\n",
    "    def handle_login(self):\n",
    "        username = self.username_entry.get()\n",
    "        password = self.password_entry.get()\n",
    "        remember = self.remember_var.get()\n",
    "\n",
    "        print(\"Username:\", username)\n",
    "        print(\"Password:\", password)\n",
    "        print(\"Remember Me:\", remember)\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app = LoginScreen()\n",
    "    app.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ae2c09af-5c0b-4dbd-ad3d-fef169facd93",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
