{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "389bf73d-36eb-4ff1-a4a0-37a31ab13ebe",
   "metadata": {},
   "outputs": [],
   "source": [
    "import customtkinter as ctk\n",
    "\n",
    "# ==========================================\n",
    "# APP APPEARANCE\n",
    "# ==========================================\n",
    "ctk.set_appearance_mode(\"light\")\n",
    "\n",
    "# ==========================================\n",
    "# RISK DETECTION KEYWORDS\n",
    "# ==========================================\n",
    "\n",
    "risk_keywords = {\n",
    "\n",
    "    # MOVEMENT / CONTROL\n",
    "    \"cannot leave\": 45,\n",
    "    \"not allowed to leave\": 45,\n",
    "    \"leave\": 10,\n",
    "    \"locked\": 40,\n",
    "    \"restricted\": 30,\n",
    "\n",
    "    # DOCUMENT CONTROL\n",
    "    \"passport\": 45,\n",
    "    \"documents\": 35,\n",
    "    \"id withheld\": 35,\n",
    "\n",
    "    # LABOUR EXPLOITATION\n",
    "    \"unpaid\": 35,\n",
    "    \"without being paid\": 40,\n",
    "    \"not paid\": 35,\n",
    "    \"salary withheld\": 35,\n",
    "    \"working for free\": 45,\n",
    "    \"forced to work\": 45,\n",
    "    \"worked for years\": 25,\n",
    "    \"long hours\": 20,\n",
    "\n",
    "    # THREATS / COERCION\n",
    "    \"threat\": 30,\n",
    "    \"threatening\": 30,\n",
    "    \"threatened\": 30,\n",
    "    \"fear\": 15,\n",
    "    \"unsafe\": 20,\n",
    "    \"afraid\": 20,\n",
    "    \"forced\": 35,\n",
    "    \"coercion\": 40,\n",
    "\n",
    "    # TRAFFICKING\n",
    "    \"trafficking\": 50,\n",
    "    \"false promise\": 40,\n",
    "    \"recruited\": 20,\n",
    "    \"transported\": 25,\n",
    "\n",
    "    # CHILD EXPLOITATION\n",
    "    \"underage\": 45,\n",
    "    \"child labour\": 50,\n",
    "\n",
    "    # ISOLATION\n",
    "    \"isolated\": 25,\n",
    "    \"monitored\": 20,\n",
    "    \"not allowed contact\": 35\n",
    "}\n",
    "# ==========================================\n",
    "# ANALYZE RISK FUNCTION\n",
    "# ==========================================\n",
    "def analyze_risk():\n",
    "\n",
    "    text = situation_textbox.get(\"1.0\", \"end\").lower()\n",
    "\n",
    "    score = 0\n",
    "\n",
    "    found_indicators = []\n",
    "\n",
    "    for keyword, points in risk_keywords.items():\n",
    "\n",
    "        if keyword in text:\n",
    "\n",
    "            score += points\n",
    "            found_indicators.append(keyword)\n",
    "\n",
    "    # DETERMINE RISK LEVEL\n",
    "\n",
    "    if score >= 70:\n",
    "\n",
    "        risk_level = \"HIGH RISK\"\n",
    "        color = \"red\"\n",
    "\n",
    "    elif score >= 35:\n",
    "\n",
    "        risk_level = \"CAUTION\"\n",
    "        color = \"orange\"\n",
    "\n",
    "    else:\n",
    "\n",
    "        risk_level = \"LOW RISK\"\n",
    "        color = \"green\"\n",
    "\n",
    "    # UPDATE RISK RESULT\n",
    "\n",
    "    risk_result_label.configure(\n",
    "        text=risk_level,\n",
    "        text_color=color\n",
    "    )\n",
    "\n",
    "    # UPDATE INDICATORS FOUND\n",
    "\n",
    "    if found_indicators:\n",
    "\n",
    "        indicators_label.configure(\n",
    "            text=\"Indicators Found:\\n• \" +\n",
    "            \"\\n• \".join(found_indicators)\n",
    "        )\n",
    "\n",
    "    else:\n",
    "\n",
    "        indicators_label.configure(\n",
    "            text=\"No major indicators detected.\"\n",
    "        )\n",
    "\n",
    "# ==========================================\n",
    "# MAIN WINDOW\n",
    "# ==========================================\n",
    "root = ctk.CTk()\n",
    "\n",
    "root.geometry(\"1440x900\")\n",
    "root.title(\"SafePath - Situation Checker\")\n",
    "\n",
    "# ==========================================\n",
    "# COLOR PALETTE\n",
    "# ==========================================\n",
    "COLOR_SIDEBAR = \"#4B1E0F\"\n",
    "COLOR_WORKSPACE_BG = \"#F3EBDD\"\n",
    "COLOR_PANEL = \"#F7F0E4\"\n",
    "COLOR_BORDER = \"#8A4F27\"\n",
    "COLOR_BUTTON = \"#8A4F27\"\n",
    "COLOR_TEXT = \"#3E2A1F\"\n",
    "\n",
    "# ==========================================\n",
    "# SIDEBAR\n",
    "# ==========================================\n",
    "sidebar = ctk.CTkFrame(\n",
    "    root,\n",
    "    width=260,\n",
    "    fg_color=COLOR_SIDEBAR,\n",
    "    corner_radius=0\n",
    ")\n",
    "\n",
    "sidebar.pack(side=\"left\", fill=\"y\")\n",
    "sidebar.pack_propagate(False)\n",
    "\n",
    "# APP NAME\n",
    "logo = ctk.CTkLabel(\n",
    "    sidebar,\n",
    "    text=\"SafePath\",\n",
    "    font=(\"Georgia\", 30, \"bold\"),\n",
    "    text_color=\"white\"\n",
    ")\n",
    "\n",
    "logo.pack(anchor=\"w\", padx=30, pady=(40, 30))\n",
    "\n",
    "# MENU ITEMS\n",
    "menu_items = [\n",
    "    \"Dashboard\",\n",
    "    \"Situation Check\",\n",
    "    \"Report Case\",\n",
    "    \"Records\",\n",
    "    \"Insights\",\n",
    "    \"Resources\",\n",
    "    \"Echoes of Home\",\n",
    "    \"Settings\"\n",
    "]\n",
    "\n",
    "for item in menu_items:\n",
    "\n",
    "    btn = ctk.CTkButton(\n",
    "        sidebar,\n",
    "        text=item,\n",
    "        fg_color=\"#C47A3A\" if item == \"Situation Check\" else \"transparent\",\n",
    "        hover_color=\"#8A4F27\",\n",
    "        text_color=\"white\",\n",
    "        anchor=\"w\",\n",
    "        height=40,\n",
    "        font=(\"Arial\", 14)\n",
    "    )\n",
    "\n",
    "    btn.pack(fill=\"x\", padx=20, pady=5)\n",
    "\n",
    "# TAGLINE\n",
    "tagline = ctk.CTkLabel(\n",
    "    sidebar,\n",
    "    text=\"Awareness. Protection. Freedom.\",\n",
    "    font=(\"Arial\", 11, \"italic\"),\n",
    "    text_color=\"#D9C2A3\"\n",
    ")\n",
    "\n",
    "tagline.pack(side=\"bottom\", pady=25)\n",
    "\n",
    "# ==========================================\n",
    "# MAIN CONTENT AREA\n",
    "# ==========================================\n",
    "main_frame = ctk.CTkFrame(\n",
    "    root,\n",
    "    fg_color=COLOR_WORKSPACE_BG,\n",
    "    corner_radius=0\n",
    ")\n",
    "\n",
    "main_frame.pack(side=\"right\", fill=\"both\", expand=True)\n",
    "\n",
    "# PAGE TITLE\n",
    "title = ctk.CTkLabel(\n",
    "    main_frame,\n",
    "    text=\"Situation Checker\",\n",
    "    font=(\"Georgia\", 36, \"bold\"),\n",
    "    text_color=COLOR_TEXT\n",
    ")\n",
    "\n",
    "title.pack(anchor=\"nw\", padx=40, pady=(40, 5))\n",
    "\n",
    "# SUBTITLE\n",
    "subtitle = ctk.CTkLabel(\n",
    "    main_frame,\n",
    "    text=\"Analyze suspicious activity for indicators of modern slavery.\",\n",
    "    font=(\"Arial\", 15),\n",
    "    text_color=\"#5E4B3C\"\n",
    ")\n",
    "\n",
    "subtitle.pack(anchor=\"nw\", padx=40, pady=(0, 30))\n",
    "\n",
    "# ==========================================\n",
    "# INPUT PANEL\n",
    "# ==========================================\n",
    "analysis_frame = ctk.CTkFrame(\n",
    "    main_frame,\n",
    "    fg_color=COLOR_PANEL,\n",
    "    border_width=2,\n",
    "    border_color=COLOR_BORDER,\n",
    "    corner_radius=15,\n",
    "    height=180\n",
    ")\n",
    "\n",
    "analysis_frame.pack(fill=\"x\", padx=40)\n",
    "\n",
    "analysis_frame.pack_propagate(False)\n",
    "\n",
    "# TEXTBOX\n",
    "situation_textbox = ctk.CTkTextbox(\n",
    "    analysis_frame,\n",
    "    height=100,\n",
    "    fg_color=\"#E9D8BE\",\n",
    "    border_color=COLOR_BORDER,\n",
    "    border_width=1,\n",
    "    text_color=COLOR_TEXT,\n",
    "    font=(\"Arial\", 14)\n",
    ")\n",
    "\n",
    "situation_textbox.pack(\n",
    "    fill=\"x\",\n",
    "    padx=30,\n",
    "    pady=(25, 15)\n",
    ")\n",
    "\n",
    "situation_textbox.insert(\n",
    "    \"1.0\",\n",
    "    \"Describe the situation in details...\"\n",
    ")\n",
    "\n",
    "# ANALYZE BUTTON\n",
    "run_button = ctk.CTkButton(\n",
    "    analysis_frame,\n",
    "    text=\"Run Risk Analysis\",\n",
    "    command=analyze_risk,\n",
    "    fg_color=COLOR_BUTTON,\n",
    "    hover_color=\"#A44E25\",\n",
    "    text_color=\"white\",\n",
    "    width=180,\n",
    "    height=40,\n",
    "    corner_radius=10\n",
    ")\n",
    "\n",
    "run_button.pack(anchor=\"e\", padx=30)\n",
    "\n",
    "# ==========================================\n",
    "# LOWER SECTION CONTAINER\n",
    "# ==========================================\n",
    "bottom_frame = ctk.CTkFrame(\n",
    "    main_frame,\n",
    "    fg_color=\"transparent\"\n",
    ")\n",
    "\n",
    "bottom_frame.pack(\n",
    "    fill=\"both\",\n",
    "    expand=True,\n",
    "    padx=40,\n",
    "    pady=30\n",
    ")\n",
    "\n",
    "# ==========================================\n",
    "# LEFT RESULT PANEL\n",
    "# ==========================================\n",
    "meter_frame = ctk.CTkFrame(\n",
    "    bottom_frame,\n",
    "    width=500,\n",
    "    fg_color=COLOR_PANEL,\n",
    "    border_width=2,\n",
    "    border_color=COLOR_BORDER,\n",
    "    corner_radius=15\n",
    ")\n",
    "\n",
    "meter_frame.pack(side=\"left\", fill=\"both\", expand=True)\n",
    "\n",
    "meter_frame.pack_propagate(False)\n",
    "\n",
    "# PLACEHOLDER GAUGE\n",
    "gauge_canvas = ctk.CTkCanvas(\n",
    "    meter_frame,\n",
    "    width=220,\n",
    "    height=220,\n",
    "    bg=\"#F7F0E4\",\n",
    "    highlightthickness=0\n",
    ")\n",
    "\n",
    "gauge_canvas.pack(pady=(30, 10))\n",
    "\n",
    "# ARC\n",
    "gauge_canvas.create_arc(\n",
    "    20,\n",
    "    20,\n",
    "    200,\n",
    "    200,\n",
    "    start=30,\n",
    "    extent=300,\n",
    "    style=\"arc\",\n",
    "    width=2\n",
    ")\n",
    "\n",
    "# NEEDLE\n",
    "gauge_canvas.create_line(\n",
    "    110,\n",
    "    110,\n",
    "    160,\n",
    "    70,\n",
    "    width=3\n",
    ")\n",
    "\n",
    "# CENTER DOT\n",
    "gauge_canvas.create_oval(\n",
    "    95,\n",
    "    95,\n",
    "    125,\n",
    "    125,\n",
    "    fill=\"#F3EBDD\"\n",
    ")\n",
    "\n",
    "# RISK RESULT LABEL\n",
    "risk_result_label = ctk.CTkLabel(\n",
    "    meter_frame,\n",
    "    text=\"Awaiting Analysis\",\n",
    "    font=(\"Georgia\", 28, \"bold\"),\n",
    "    text_color=\"#5E4B3C\"\n",
    ")\n",
    "\n",
    "risk_result_label.pack(pady=20)\n",
    "\n",
    "# ==========================================\n",
    "# RIGHT INDICATORS PANEL\n",
    "# ==========================================\n",
    "right_panel = ctk.CTkFrame(\n",
    "    bottom_frame,\n",
    "    width=280,\n",
    "    fg_color=\"#6B3F1D\",\n",
    "    corner_radius=15\n",
    ")\n",
    "\n",
    "right_panel.pack(side=\"right\", fill=\"y\", padx=(20,0))\n",
    "\n",
    "right_panel.pack_propagate(False)\n",
    "\n",
    "# PANEL TITLE\n",
    "panel_title = ctk.CTkLabel(\n",
    "    right_panel,\n",
    "    text=\"Common Indicators\",\n",
    "    font=(\"Georgia\", 20, \"bold\"),\n",
    "    text_color=\"white\"\n",
    ")\n",
    "\n",
    "panel_title.pack(anchor=\"w\", padx=20, pady=(25,20))\n",
    "\n",
    "# LEGEND\n",
    "legend1 = ctk.CTkLabel(\n",
    "    right_panel,\n",
    "    text=\"🔴 High Risk\",\n",
    "    font=(\"Arial\", 14),\n",
    "    text_color=\"white\"\n",
    ")\n",
    "\n",
    "legend1.pack(anchor=\"w\", padx=20, pady=5)\n",
    "\n",
    "legend2 = ctk.CTkLabel(\n",
    "    right_panel,\n",
    "    text=\"🟠 Caution\",\n",
    "    font=(\"Arial\", 14),\n",
    "    text_color=\"white\"\n",
    ")\n",
    "\n",
    "legend2.pack(anchor=\"w\", padx=20, pady=5)\n",
    "\n",
    "legend3 = ctk.CTkLabel(\n",
    "    right_panel,\n",
    "    text=\"🟢 Low Risk\",\n",
    "    font=(\"Arial\", 14),\n",
    "    text_color=\"white\"\n",
    ")\n",
    "\n",
    "legend3.pack(anchor=\"w\", padx=20, pady=5)\n",
    "\n",
    "# INDICATORS OUTPUT\n",
    "indicators_label = ctk.CTkLabel(\n",
    "    right_panel,\n",
    "    text=\"No indicators yet.\",\n",
    "    justify=\"left\",\n",
    "    font=(\"Arial\", 14),\n",
    "    text_color=\"#F3EBDD\"\n",
    ")\n",
    "\n",
    "indicators_label.pack(\n",
    "    anchor=\"w\",\n",
    "    padx=20,\n",
    "    pady=(30,10)\n",
    ")\n",
    "\n",
    "# ==========================================\n",
    "# MAIN LOOP\n",
    "# ==========================================\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "49d54ea5-9cc6-41c1-ae59-3ff64cf0e559",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
